import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
plugins {
    java // Used by Spring plugin to create jar
    id("org.springframework.boot").version(Versions.springVersion)

    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version(Versions.kotlinVersion)

    // Kotlin compiler plugin to allow spring requirements for the language
    id("org.jetbrains.kotlin.plugin.allopen").version(Versions.kotlinVersion)
    id("org.jetbrains.kotlin.plugin.noarg").version(Versions.kotlinVersion)
    id("org.jetbrains.kotlin.plugin.spring").version(Versions.kotlinVersion)
    // id("org.jetbrains.kotlin.plugin.jpa").version(Versions.kotlinVersion) // TODO("enable for jpa")
}
apply(plugin = "io.spring.dependency-management")

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    // implementation("org.springframework.boot:spring-boot-starter-data-jpa") // TODO("enable for jpa")
    // implementation("org.springframework.boot:spring-boot-starter-security") // TODO("enable for security")
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")

    // runtimeOnly("org.springframework.boot:spring-boot-devtools") // I don't think this will work with kotlin
    // runtimeOnly("com.h2database:h2") // TODO("enable for embedded db")
    compileOnly("org.springframework.boot:spring-boot-configuration-processor")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.springframework.security:spring-security-test")

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

tasks {
    withType<KotlinCompile> {
        kotlinOptions.jvmTarget = "1.8"
    }
}
